window.__PLANBOARD_CONFIG__ = window.__PLANBOARD_CONFIG__ || {
  DATA_SOURCE: "rest",
  API_BASE_URL: "",
  FIREBASE_API_KEY: "",
  FIREBASE_AUTH_DOMAIN: "",
  FIREBASE_PROJECT_ID: "",
  FIREBASE_STORAGE_BUCKET: "",
  FIREBASE_MESSAGING_SENDER_ID: "",
  FIREBASE_APP_ID: "",
  FIREBASE_SDK_VERSION: "12.4.0",
};
